// <auto-generated />
using System;
using DoAn_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DoAn_API.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20231216021432_AddTblDB")]
    partial class AddTblDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DoAn_API.Models.ChiTietNhomModel", b =>
                {
                    b.Property<string>("ChiTietNhomID")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("NhomID")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("SinhVienID")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("ChiTietNhomID");

                    b.HasIndex("NhomID");

                    b.HasIndex("SinhVienID");

                    b.ToTable("ChiTietNhom");
                });

            modelBuilder.Entity("DoAn_API.Models.ChuyenNganhModel", b =>
                {
                    b.Property<string>("ChuyenNganhID")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("TenChuyenNganh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ChuyenNganhID");

                    b.ToTable("ChuyenNganh");
                });

            modelBuilder.Entity("DoAn_API.Models.DeTaiModel", b =>
                {
                    b.Property<string>("DeTaiID")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("ChuyenNganhID")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("GiangVienID")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("LoaiDeTaiID")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NienKhoaID")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("SinhVienID")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("TenDeTai")
                        .HasMaxLength(2555)
                        .HasColumnType("nvarchar(2555)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("DeTaiID");

                    b.HasIndex("ChuyenNganhID");

                    b.HasIndex("GiangVienID");

                    b.HasIndex("LoaiDeTaiID");

                    b.HasIndex("NienKhoaID");

                    b.HasIndex("SinhVienID");

                    b.ToTable("DeTai");
                });

            modelBuilder.Entity("DoAn_API.Models.DuyetDeTaiModel", b =>
                {
                    b.Property<string>("DuyetID")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("DeTaiID")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("GiangVienID")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<DateTime>("NgayDuyet")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("DuyetID");

                    b.HasIndex("DeTaiID");

                    b.HasIndex("GiangVienID");

                    b.ToTable("DuyetDeTai");
                });

            modelBuilder.Entity("DoAn_API.Models.GiangVienModel", b =>
                {
                    b.Property<string>("GiangVienID")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("KhoaID")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhomQuyenID")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SDT")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("GiangVienID");

                    b.HasIndex("KhoaID");

                    b.HasIndex("NhomQuyenID");

                    b.ToTable("GiangVien");
                });

            modelBuilder.Entity("DoAn_API.Models.KhoaModel", b =>
                {
                    b.Property<string>("KhoaID")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("TenKhoa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("KhoaID");

                    b.ToTable("Khoa");
                });

            modelBuilder.Entity("DoAn_API.Models.LoaiDeTaiModel", b =>
                {
                    b.Property<string>("LoaiDeTaiID")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("TenLoaiDeTai")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("LoaiDeTaiID");

                    b.ToTable("LoaiDeTai");
                });

            modelBuilder.Entity("DoAn_API.Models.LopModel", b =>
                {
                    b.Property<string>("LopID")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("KhoaID")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("TenLop")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("LopID");

                    b.HasIndex("KhoaID");

                    b.ToTable("Lop");
                });

            modelBuilder.Entity("DoAn_API.Models.NhomModel", b =>
                {
                    b.Property<string>("NhomID")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("DeTaiID")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("TenNhom")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("NhomID");

                    b.HasIndex("DeTaiID");

                    b.ToTable("Nhom");
                });

            modelBuilder.Entity("DoAn_API.Models.NhomQuyenModel", b =>
                {
                    b.Property<string>("NhomQuyenID")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenNhomQuyen")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("NhomQuyenID");

                    b.ToTable("NhomQuyen");
                });

            modelBuilder.Entity("DoAn_API.Models.NienKhoaModel", b =>
                {
                    b.Property<string>("NienKhoaID")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("TenNienKhoa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("NienKhoaID");

                    b.ToTable("NienKhoa");
                });

            modelBuilder.Entity("DoAn_API.Models.SinhVienModel", b =>
                {
                    b.Property<string>("SinhVienID")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LopID")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhomQuyenID")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SDT")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SinhVienID");

                    b.HasIndex("LopID");

                    b.HasIndex("NhomQuyenID");

                    b.ToTable("SinhVien");
                });

            modelBuilder.Entity("DoAn_API.Models.ThoiGianDangKyModel", b =>
                {
                    b.Property<string>("ThoiGianDangKyID")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<DateTime>("BatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("KetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LoaiDeTaiID")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.HasKey("ThoiGianDangKyID");

                    b.HasIndex("LoaiDeTaiID");

                    b.ToTable("ThoiGianDangKy");
                });

            modelBuilder.Entity("DoAn_API.Models.ChiTietNhomModel", b =>
                {
                    b.HasOne("DoAn_API.Models.NhomModel", "Nhom")
                        .WithMany()
                        .HasForeignKey("NhomID");

                    b.HasOne("DoAn_API.Models.SinhVienModel", "SinhVien")
                        .WithMany()
                        .HasForeignKey("SinhVienID");

                    b.Navigation("Nhom");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("DoAn_API.Models.DeTaiModel", b =>
                {
                    b.HasOne("DoAn_API.Models.ChuyenNganhModel", "ChuyenNganh")
                        .WithMany()
                        .HasForeignKey("ChuyenNganhID");

                    b.HasOne("DoAn_API.Models.GiangVienModel", "GiangVien")
                        .WithMany()
                        .HasForeignKey("GiangVienID");

                    b.HasOne("DoAn_API.Models.LoaiDeTaiModel", "LoaiDeTai")
                        .WithMany()
                        .HasForeignKey("LoaiDeTaiID");

                    b.HasOne("DoAn_API.Models.NienKhoaModel", "NienKhoa")
                        .WithMany()
                        .HasForeignKey("NienKhoaID");

                    b.HasOne("DoAn_API.Models.SinhVienModel", "SinhVien")
                        .WithMany()
                        .HasForeignKey("SinhVienID");

                    b.Navigation("ChuyenNganh");

                    b.Navigation("GiangVien");

                    b.Navigation("LoaiDeTai");

                    b.Navigation("NienKhoa");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("DoAn_API.Models.DuyetDeTaiModel", b =>
                {
                    b.HasOne("DoAn_API.Models.DeTaiModel", "DeTai")
                        .WithMany()
                        .HasForeignKey("DeTaiID");

                    b.HasOne("DoAn_API.Models.GiangVienModel", "GiangVien")
                        .WithMany()
                        .HasForeignKey("GiangVienID");

                    b.Navigation("DeTai");

                    b.Navigation("GiangVien");
                });

            modelBuilder.Entity("DoAn_API.Models.GiangVienModel", b =>
                {
                    b.HasOne("DoAn_API.Models.KhoaModel", "Khoa")
                        .WithMany()
                        .HasForeignKey("KhoaID");

                    b.HasOne("DoAn_API.Models.NhomQuyenModel", "NhomQuyen")
                        .WithMany()
                        .HasForeignKey("NhomQuyenID");

                    b.Navigation("Khoa");

                    b.Navigation("NhomQuyen");
                });

            modelBuilder.Entity("DoAn_API.Models.LopModel", b =>
                {
                    b.HasOne("DoAn_API.Models.KhoaModel", "Khoa")
                        .WithMany()
                        .HasForeignKey("KhoaID");

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("DoAn_API.Models.NhomModel", b =>
                {
                    b.HasOne("DoAn_API.Models.DeTaiModel", "DeTai")
                        .WithMany()
                        .HasForeignKey("DeTaiID");

                    b.Navigation("DeTai");
                });

            modelBuilder.Entity("DoAn_API.Models.SinhVienModel", b =>
                {
                    b.HasOne("DoAn_API.Models.LopModel", "Lop")
                        .WithMany()
                        .HasForeignKey("LopID");

                    b.HasOne("DoAn_API.Models.NhomQuyenModel", "NhomQuyen")
                        .WithMany()
                        .HasForeignKey("NhomQuyenID");

                    b.Navigation("Lop");

                    b.Navigation("NhomQuyen");
                });

            modelBuilder.Entity("DoAn_API.Models.ThoiGianDangKyModel", b =>
                {
                    b.HasOne("DoAn_API.Models.LoaiDeTaiModel", "LoaiDeTai")
                        .WithMany()
                        .HasForeignKey("LoaiDeTaiID");

                    b.Navigation("LoaiDeTai");
                });
#pragma warning restore 612, 618
        }
    }
}
